//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace SpellToScore.DatabaseWebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DatabaseWebServiceReference.DatabaseWebServiceSoap")]
    public interface DatabaseWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetLoggedInUserId", ReplyAction="*")]
        System.IAsyncResult BeginGetLoggedInUserId(System.AsyncCallback callback, object asyncState);
        
        int EndGetLoggedInUserId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetLoggedInUserName", ReplyAction="*")]
        System.IAsyncResult BeginGetLoggedInUserName(SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameRequest request, System.AsyncCallback callback, object asyncState);
        
        SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameResponse EndGetLoggedInUserName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SaveScore", ReplyAction="*")]
        System.IAsyncResult BeginSaveScore(int userId, int score, System.AsyncCallback callback, object asyncState);
        
        bool EndSaveScore(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/LoadScores", ReplyAction="*")]
        System.IAsyncResult BeginLoadScores(SpellToScore.DatabaseWebServiceReference.LoadScoresRequest request, System.AsyncCallback callback, object asyncState);
        
        SpellToScore.DatabaseWebServiceReference.LoadScoresResponse EndLoadScores(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoggedInUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoggedInUserName", Namespace="http://tempuri.org/", Order=0)]
        public SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameRequestBody Body;
        
        public GetLoggedInUserNameRequest() {
        }
        
        public GetLoggedInUserNameRequest(SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLoggedInUserNameRequestBody {
        
        public GetLoggedInUserNameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoggedInUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoggedInUserNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameResponseBody Body;
        
        public GetLoggedInUserNameResponse() {
        }
        
        public GetLoggedInUserNameResponse(SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoggedInUserNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLoggedInUserNameResult;
        
        public GetLoggedInUserNameResponseBody() {
        }
        
        public GetLoggedInUserNameResponseBody(string GetLoggedInUserNameResult) {
            this.GetLoggedInUserNameResult = GetLoggedInUserNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadScoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadScores", Namespace="http://tempuri.org/", Order=0)]
        public SpellToScore.DatabaseWebServiceReference.LoadScoresRequestBody Body;
        
        public LoadScoresRequest() {
        }
        
        public LoadScoresRequest(SpellToScore.DatabaseWebServiceReference.LoadScoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadScoresRequestBody {
        
        public LoadScoresRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadScoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadScoresResponse", Namespace="http://tempuri.org/", Order=0)]
        public SpellToScore.DatabaseWebServiceReference.LoadScoresResponseBody Body;
        
        public LoadScoresResponse() {
        }
        
        public LoadScoresResponse(SpellToScore.DatabaseWebServiceReference.LoadScoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadScoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadScoresResult;
        
        public LoadScoresResponseBody() {
        }
        
        public LoadScoresResponseBody(string LoadScoresResult) {
            this.LoadScoresResult = LoadScoresResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DatabaseWebServiceSoapChannel : SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLoggedInUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLoggedInUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLoggedInUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLoggedInUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadScoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoadScoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseWebServiceSoapClient : System.ServiceModel.ClientBase<SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap>, SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap {
        
        private BeginOperationDelegate onBeginGetLoggedInUserIdDelegate;
        
        private EndOperationDelegate onEndGetLoggedInUserIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetLoggedInUserIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLoggedInUserNameDelegate;
        
        private EndOperationDelegate onEndGetLoggedInUserNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetLoggedInUserNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveScoreDelegate;
        
        private EndOperationDelegate onEndSaveScoreDelegate;
        
        private System.Threading.SendOrPostCallback onSaveScoreCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoadScoresDelegate;
        
        private EndOperationDelegate onEndLoadScoresDelegate;
        
        private System.Threading.SendOrPostCallback onLoadScoresCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DatabaseWebServiceSoapClient() {
        }
        
        public DatabaseWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetLoggedInUserIdCompletedEventArgs> GetLoggedInUserIdCompleted;
        
        public event System.EventHandler<GetLoggedInUserNameCompletedEventArgs> GetLoggedInUserNameCompleted;
        
        public event System.EventHandler<SaveScoreCompletedEventArgs> SaveScoreCompleted;
        
        public event System.EventHandler<LoadScoresCompletedEventArgs> LoadScoresCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap.BeginGetLoggedInUserId(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLoggedInUserId(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap.EndGetLoggedInUserId(System.IAsyncResult result) {
            return base.Channel.EndGetLoggedInUserId(result);
        }
        
        private System.IAsyncResult OnBeginGetLoggedInUserId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap)(this)).BeginGetLoggedInUserId(callback, asyncState);
        }
        
        private object[] OnEndGetLoggedInUserId(System.IAsyncResult result) {
            int retVal = ((SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap)(this)).EndGetLoggedInUserId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLoggedInUserIdCompleted(object state) {
            if ((this.GetLoggedInUserIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLoggedInUserIdCompleted(this, new GetLoggedInUserIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLoggedInUserIdAsync() {
            this.GetLoggedInUserIdAsync(null);
        }
        
        public void GetLoggedInUserIdAsync(object userState) {
            if ((this.onBeginGetLoggedInUserIdDelegate == null)) {
                this.onBeginGetLoggedInUserIdDelegate = new BeginOperationDelegate(this.OnBeginGetLoggedInUserId);
            }
            if ((this.onEndGetLoggedInUserIdDelegate == null)) {
                this.onEndGetLoggedInUserIdDelegate = new EndOperationDelegate(this.OnEndGetLoggedInUserId);
            }
            if ((this.onGetLoggedInUserIdCompletedDelegate == null)) {
                this.onGetLoggedInUserIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLoggedInUserIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetLoggedInUserIdDelegate, null, this.onEndGetLoggedInUserIdDelegate, this.onGetLoggedInUserIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap.BeginGetLoggedInUserName(SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLoggedInUserName(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetLoggedInUserName(System.AsyncCallback callback, object asyncState) {
            SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameRequest inValue = new SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameRequest();
            inValue.Body = new SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameRequestBody();
            return ((SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap)(this)).BeginGetLoggedInUserName(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameResponse SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap.EndGetLoggedInUserName(System.IAsyncResult result) {
            return base.Channel.EndGetLoggedInUserName(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetLoggedInUserName(System.IAsyncResult result) {
            SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameResponse retVal = ((SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap)(this)).EndGetLoggedInUserName(result);
            return retVal.Body.GetLoggedInUserNameResult;
        }
        
        private System.IAsyncResult OnBeginGetLoggedInUserName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetLoggedInUserName(callback, asyncState);
        }
        
        private object[] OnEndGetLoggedInUserName(System.IAsyncResult result) {
            string retVal = this.EndGetLoggedInUserName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLoggedInUserNameCompleted(object state) {
            if ((this.GetLoggedInUserNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLoggedInUserNameCompleted(this, new GetLoggedInUserNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLoggedInUserNameAsync() {
            this.GetLoggedInUserNameAsync(null);
        }
        
        public void GetLoggedInUserNameAsync(object userState) {
            if ((this.onBeginGetLoggedInUserNameDelegate == null)) {
                this.onBeginGetLoggedInUserNameDelegate = new BeginOperationDelegate(this.OnBeginGetLoggedInUserName);
            }
            if ((this.onEndGetLoggedInUserNameDelegate == null)) {
                this.onEndGetLoggedInUserNameDelegate = new EndOperationDelegate(this.OnEndGetLoggedInUserName);
            }
            if ((this.onGetLoggedInUserNameCompletedDelegate == null)) {
                this.onGetLoggedInUserNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLoggedInUserNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetLoggedInUserNameDelegate, null, this.onEndGetLoggedInUserNameDelegate, this.onGetLoggedInUserNameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap.BeginSaveScore(int userId, int score, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveScore(userId, score, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap.EndSaveScore(System.IAsyncResult result) {
            return base.Channel.EndSaveScore(result);
        }
        
        private System.IAsyncResult OnBeginSaveScore(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            int score = ((int)(inValues[1]));
            return ((SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap)(this)).BeginSaveScore(userId, score, callback, asyncState);
        }
        
        private object[] OnEndSaveScore(System.IAsyncResult result) {
            bool retVal = ((SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap)(this)).EndSaveScore(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveScoreCompleted(object state) {
            if ((this.SaveScoreCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveScoreCompleted(this, new SaveScoreCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveScoreAsync(int userId, int score) {
            this.SaveScoreAsync(userId, score, null);
        }
        
        public void SaveScoreAsync(int userId, int score, object userState) {
            if ((this.onBeginSaveScoreDelegate == null)) {
                this.onBeginSaveScoreDelegate = new BeginOperationDelegate(this.OnBeginSaveScore);
            }
            if ((this.onEndSaveScoreDelegate == null)) {
                this.onEndSaveScoreDelegate = new EndOperationDelegate(this.OnEndSaveScore);
            }
            if ((this.onSaveScoreCompletedDelegate == null)) {
                this.onSaveScoreCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveScoreCompleted);
            }
            base.InvokeAsync(this.onBeginSaveScoreDelegate, new object[] {
                        userId,
                        score}, this.onEndSaveScoreDelegate, this.onSaveScoreCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap.BeginLoadScores(SpellToScore.DatabaseWebServiceReference.LoadScoresRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoadScores(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginLoadScores(System.AsyncCallback callback, object asyncState) {
            SpellToScore.DatabaseWebServiceReference.LoadScoresRequest inValue = new SpellToScore.DatabaseWebServiceReference.LoadScoresRequest();
            inValue.Body = new SpellToScore.DatabaseWebServiceReference.LoadScoresRequestBody();
            return ((SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap)(this)).BeginLoadScores(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SpellToScore.DatabaseWebServiceReference.LoadScoresResponse SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap.EndLoadScores(System.IAsyncResult result) {
            return base.Channel.EndLoadScores(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndLoadScores(System.IAsyncResult result) {
            SpellToScore.DatabaseWebServiceReference.LoadScoresResponse retVal = ((SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap)(this)).EndLoadScores(result);
            return retVal.Body.LoadScoresResult;
        }
        
        private System.IAsyncResult OnBeginLoadScores(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginLoadScores(callback, asyncState);
        }
        
        private object[] OnEndLoadScores(System.IAsyncResult result) {
            string retVal = this.EndLoadScores(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoadScoresCompleted(object state) {
            if ((this.LoadScoresCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoadScoresCompleted(this, new LoadScoresCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoadScoresAsync() {
            this.LoadScoresAsync(null);
        }
        
        public void LoadScoresAsync(object userState) {
            if ((this.onBeginLoadScoresDelegate == null)) {
                this.onBeginLoadScoresDelegate = new BeginOperationDelegate(this.OnBeginLoadScores);
            }
            if ((this.onEndLoadScoresDelegate == null)) {
                this.onEndLoadScoresDelegate = new EndOperationDelegate(this.OnEndLoadScores);
            }
            if ((this.onLoadScoresCompletedDelegate == null)) {
                this.onLoadScoresCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoadScoresCompleted);
            }
            base.InvokeAsync(this.onBeginLoadScoresDelegate, null, this.onEndLoadScoresDelegate, this.onLoadScoresCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap CreateChannel() {
            return new DatabaseWebServiceSoapClientChannel(this);
        }
        
        private class DatabaseWebServiceSoapClientChannel : ChannelBase<SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap>, SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap {
            
            public DatabaseWebServiceSoapClientChannel(System.ServiceModel.ClientBase<SpellToScore.DatabaseWebServiceReference.DatabaseWebServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetLoggedInUserId(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetLoggedInUserId", _args, callback, asyncState);
                return _result;
            }
            
            public int EndGetLoggedInUserId(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("GetLoggedInUserId", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLoggedInUserName(SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetLoggedInUserName", _args, callback, asyncState);
                return _result;
            }
            
            public SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameResponse EndGetLoggedInUserName(System.IAsyncResult result) {
                object[] _args = new object[0];
                SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameResponse _result = ((SpellToScore.DatabaseWebServiceReference.GetLoggedInUserNameResponse)(base.EndInvoke("GetLoggedInUserName", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveScore(int userId, int score, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = userId;
                _args[1] = score;
                System.IAsyncResult _result = base.BeginInvoke("SaveScore", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndSaveScore(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("SaveScore", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLoadScores(SpellToScore.DatabaseWebServiceReference.LoadScoresRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("LoadScores", _args, callback, asyncState);
                return _result;
            }
            
            public SpellToScore.DatabaseWebServiceReference.LoadScoresResponse EndLoadScores(System.IAsyncResult result) {
                object[] _args = new object[0];
                SpellToScore.DatabaseWebServiceReference.LoadScoresResponse _result = ((SpellToScore.DatabaseWebServiceReference.LoadScoresResponse)(base.EndInvoke("LoadScores", _args, result)));
                return _result;
            }
        }
    }
}
